### PR TITLE
Add prettier and eslint configs.

### PR DESCRIPTION
**Pull request by prodonjs**
Followed guides from:
- https://javascriptplayground.com/typescript-eslint/
- https://prettier.io/docs/en/integrating-with-linters.html
- https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin

Also installed the prettier VSCode extension https://prettier.io/docs/en/editors.html#visual-studio-code.

### CODE REVIEW

**Comment by weitingcheng** [comment]
Can we follow Google's internal typescript config?
https://g3doc.corp.google.com/javascript/typescript/g3doc/setup/vscode.md?cl=head

and use clang-format like it suggested
http://go/typescript/setup/vscode#public-extensions

**Comment by prodonjs** [comment]
Sorry I didn't send that comment before yours. Do you know if it's possible to add the google3 format to an open-source repository? I borrowed this config from https://github.com/google/gts.

**Comment by weitingcheng** [comment]
hmm, I am not sure about google3 style, but the clang-format is public library. 

Actually, we better put a linter bot in github since this extension will go open source eventually.

**Comment by prodonjs** [comment]
> hmm, I am not sure about google3 style, but the clang-format is public library.
> 
> Actually, we better put a linter bot in github since this extension will go open source eventually.

Yeah, my thoughts on this were to try to use the closest thing we can to internal Google typescript standards and the https://github.com/google/gts project seemed like a good starting place. Then I read that TSLint was being [deprecated](https://www.npmjs.com/package/tslint) in favor of ESLint so I figured I'd just grab the standard best practices from there.

**Comment by prodonjs** [comment]
I'm going to merge this so we have a common place to work from.

I added these settings in my project folder in VSCode to override the default google3 settings. 

```
{
  "editor.formatOnSave": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact"
  ],
  "tslint.enable": false,
 ...
```


We can change the linter settings or check in the `.settings` file from VSCode at a later time if we need to.

**Pull request merged**
